set test "input.char"
if {! [installtest_p]} { untested "$test"; return }
set send_human { .1 .3 1 .05 2 }

catch {
    spawn stap $srcdir/$subdir/$test.stp
    expect
    
    send -raw "abcde"
    
    expect  {
        "a\r\nb\r\nc\r\nzze\r\n" { pass "sub1" }
        timeout { fail "sub1" }
    }
    
    send -h -raw "12345\n"
    
    expect {
        "1\r\n2\r\n3\r\n4\r\n5\r\n\r\n" { pass "sub2" }
        timeout { fail "sub2" }
    }
}

kill -INT -[exp_pid] 3
catch {close}; catch {wait}
